export const ROUTES = {
  dashboard: '/',
  liveVehicles: '/live-vehicles',
  savedVehicles: '/saved-vehicles',
  vehicleDetails: '/vehicle-details',
  driverList: '/driver-list',
  reports: '/reports',
  analytics: '/analytics',
  map: '/map',
  users: '/users',
  sweeperMonitoring: '/sweeper-monitoring',
  distanceReport: '/distance-report',
  vehicleHistory: '/vehicle-history',
  projects: '/projects',
  projectDetail: '/projects/:id',
  roads: '/roads',
  roadCreate: '/roads/create',
  roadDetail: '/roads/:id',
  roadEdit: '/roads/:id/edit',
  machines: '/machines',
  machineCreate: '/machines/create',
  machineDetail: '/machines/:id',
  machineEdit: '/machines/:id/edit',
  sweepingPlans: '/sweeping-plans',
  machineTracking: '/machine-tracking',
  plannedVsActual: '/planned-vs-actual',
  login: '/login',
  signup: '/signup',
};

export const ROUTE_TITLES = {
  [ROUTES.dashboard]: 'Dashboard',
  [ROUTES.liveVehicles]: 'Live Vehicles',
  [ROUTES.savedVehicles]: 'Saved Data',
  [ROUTES.vehicleDetails]: 'Vehicle Details',
  [ROUTES.driverList]: 'Driver List',
  [ROUTES.reports]: 'Reports',
  [ROUTES.analytics]: 'Analytics',
  [ROUTES.map]: 'Live Map Tracking',
  [ROUTES.users]: 'User Management',
  [ROUTES.sweeperMonitoring]: 'Sweeper Monitoring',
  [ROUTES.distanceReport]: 'Distance Report',
  [ROUTES.vehicleHistory]: 'Vehicle History',
  [ROUTES.projects]: 'Projects',
  [ROUTES.roads]: 'Roads',
  [ROUTES.machines]: 'Machines',
  [ROUTES.sweepingPlans]: 'Daily Sweeping Plan',
  [ROUTES.machineTracking]: 'Machine Tracking',
  [ROUTES.plannedVsActual]: 'Planned vs Actual',
};
