export const ROUTES = {
  dashboard: '/',
  liveVehicles: '/live-vehicles',
  savedVehicles: '/saved-vehicles',
  vehicleDetails: '/vehicle-details',
  driverList: '/driver-list',
  reports: '/reports',
  analytics: '/analytics',
  map: '/map',
  users: '/users',
  sweeperMonitoring: '/sweeper-monitoring',
  distanceReport: '/distance-report',
  vehicleHistory: '/vehicle-history',
  login: '/login',
  signup: '/signup',
};

export const ROUTE_TITLES = {
  [ROUTES.dashboard]: 'Dashboard',
  [ROUTES.liveVehicles]: 'Live Vehicles',
  [ROUTES.savedVehicles]: 'Saved Data',
  [ROUTES.vehicleDetails]: 'Vehicle Details',
  [ROUTES.driverList]: 'Driver List',
  [ROUTES.reports]: 'Reports',
  [ROUTES.analytics]: 'Analytics',
  [ROUTES.map]: 'Live Map Tracking',
  [ROUTES.users]: 'User Management',
  [ROUTES.sweeperMonitoring]: 'Sweeper Monitoring',
  [ROUTES.distanceReport]: 'Distance Report',
  [ROUTES.vehicleHistory]: 'Vehicle History',
};
